### ISSUE TITLE
PIC to PI comms

### ISSUE THREAD

**Issue by NicholasAECE** [timmybyster/CCB#1]
RX appears to stop working on the PIC for data coming from the PI. This means that the PI can no longer query data. Changes on cable-faults or KS are still reported to PI correctly which indicates Tx line still stable. Currently only solution is to reset the micro-controller which immediately corrects the fault. This indicates the fault is on the PIC side as no changes are made to the PI.

**Comment by timothyBuckley12** [comment]
This is not a hardware or Pic problem. The receive algorithm for packets coming from the PI is flawed.
On receiving a packet from the PI the IBC is checking for a the packet length and then waiting to receive that number of bytes before it is resets the buffer and is ready to to receive a new packet. This is flawed as in the case where a packet is interrupted an only partially received the reference of the buffer is incorrect and the next packet is written into the buffer of the previous until the correct number of bytes is received. 

For example say two packets are sent by the pi:
AAAA010001DD5C & AAAA020001ABCD
if the first packet is interrupted and only AAAA010001 is recieved the IBC will then complete the packet with AAAA. and then receive another packet 020001ABCD. This means that there are now two packets one with an incorrect CRC and another that is incomplete waiting for 2 more bytes to complete it. This will happen perpetually until the PIC is reset and the buffer index cleared.

A solution to this is to upgrade this algorithm to reset the buffer index whenever the start HEADER AAAA is received. This may be problematic as there is a very small possibility that there may be either a CRC AAAA or a serial number AAAA. It must be discussed how best to solve this. Potentially combining the reset under AAAA condition with a successful packet reception timeout may be a solution. So if after a period of time a complete packet has not been received and AAAA is received we can assume that it the buffer index must be reset.
